### ISSUE TITLE
test fail on julia-0.5

### ISSUE THREAD

**Issue by nlooije** [UCL/LatBo.jl#16]
Hi,

I was trying out your module and found that there are several errors while running `Pkg.test("LatBo")`:

 > ERROR: LoadError: LoadError: UndefVarError: FloatingPoint not defined
 > while loading .\LatBo\src\LatBo.jl, in expression starting on line 8

`FloatingPoint` is no longer [supported](https://github.com/JuliaLang/julia/issues/8142). Changing to `AbstractFloat` yields the next error:

 > ERROR: LoadError: LoadError: LoadError: syntax: "<" is not a unary operator
 > while loading .\LatBo\src\indices/indices.jl, in expression starting on line 17

which is solved by changing from `=<` to `<=`.  The next error has me stumped:

 > ERROR: LoadError: LoadError: LoadError: MethodError: no method matching start(::Type{Integer})
 > Closest candidates are:
 >   start(::SimpleVector) at essentials.jl:170
 >   start(::Base.MethodList) at reflection.jl:258
 >   start(::IntSet) at intset.jl:184
 > while loading C:\Users\niels\.julia\v0.5\LatBo\src\indices/indices.jl, in expression starting on line 21

I don't have enough experience with Julia to fix this error. Can you update this for Julia-0.5, please?

**Comment by mdavezac** [comment]
I'll take a look. I think it comes from an older way specifying variational arguments.

```Julia
index(kernel::Indexing, indices::(Integer...)) = index(kernel::Indexing, collect(indices))
```

should now read

```Julia
index{I <: Integer}(kernel::Indexing, indices::Vararg{I}) = index(kernel::Indexing, collect(indices))
```

For what it is worth, I'm not sure I've chose the most efficient way to do Lattice Boltzmann on Julia, especially with respect to [this tip](http://docs.julialang.org/en/release-0.5/manual/performance-tips/#avoid-containers-with-abstract-type-parameters).

**Comment by mdavezac** [comment]
Got the tests  running locally.
Now need to check the examples, at least pipe.ipynb

**Comment by mdavezac** [comment]
Done!
The [pipe](https://github.com/UCL/LatBo.jl/blob/master/examples/pipe.ipynb) and [profiling](https://github.com/UCL/LatBo.jl/blob/master/examples/Profiling.ipynb) notebooks both work in examples.
You can run them using [IJulia](https://github.com/JuliaLang/IJulia.jl).

**Comment by nlooije** [comment]
Great, thx for fixing this!
